name: Release Workflow

# Se activa automáticamente al hacer push de un tag o manualmente desde la UI de Actions.
on:
  push:
    branches:
      - main  # Trigger al hacer push a main
  workflow_dispatch:  # Habilita ejecución manual

jobs:
  release:
    if: ${{ github.repository == 'ch0cohub/choco-hub-1' }}
    name: Create GitHub Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Validate Tag Format
        id: validate_tag
        run: |
          current_tag=$(git describe --tags --abbrev=0)
          if [[ ! $current_tag =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "Invalid tag format: $current_tag"
            exit 1
          fi

      - name: Check if Major or Minor Version
        id: check_version
        run: |
          current_tag=$(git describe --tags --abbrev=0)
          previous_tag=$(git describe --tags --abbrev=0 HEAD^ || echo "v0.0.0")

          current_major=$(echo $current_tag | cut -d '.' -f 1 | tr -d 'v')
          previous_major=$(echo $previous_tag | cut -d '.' -f 1 | tr -d 'v')

          current_minor=$(echo $current_tag | cut -d '.' -f 2)
          previous_minor=$(echo $previous_tag | cut -d '.' -f 2)

          if [[ "$current_major" -gt "$previous_major" ]] || [[ "$current_minor" -gt "$previous_minor" ]]; then
            echo "is_release=true" >> $GITHUB_ENV
          else
            echo "is_release=false" >> $GITHUB_ENV
          fi

      - name: Stop if not Major or Minor Version
        if: env.is_release != 'true'
        run: |
          echo "This is not a major or minor version. Skipping release."
          exit 0

      - name: Generate Changelog
        id: changelog
        run: |
          current_tag=$(git describe --tags --abbrev=0)
          previous_tag=$(git describe --tags --abbrev=0 HEAD^ || echo "")

          if [ -z "$previous_tag" ]; then
            changelog=$(git log --pretty=format:"- %s (%an)")
          else
            changelog=$(git log $previous_tag..$current_tag --pretty=format:"- %s (%an)")
          fi

          echo "Changelog:"
          echo "$changelog"
          echo "changelog=$changelog" >> $GITHUB_ENV

      - name: Create GitHub Release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          release_name: ${{ github.ref_name }}
          body: ${{ env.changelog }}
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
