name: Open Pull Request in Choco2

on:
  push:
    branches:
      - CI_workflow

jobs:
  create-pr:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Git
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"

    - name: Clone choco2 repository
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        git clone https://github.com/ch0cohub/choco-hub-2.git choco2
        cd choco2
    
        git remote add choco1 https://github.com/ch0cohub/choco-hub-1.git
        git fetch choco1 CI_workflow

        git checkout -B choco1-repo-branch-30-11
        git merge --no-ff --no-edit --allow-unrelated-histories choco1/CI_workflow

        git push origin choco1-repo-branch-30-11

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v7
      with:
        token: ${{ secrets.GH_TOKEN }}
        commit-message: Sync from choco1/CI_workflow
        branch: choco1-repo-branch-30-11
        base: main
        title: Sync from choco1/CI_workflow
        body: |
          This PR merges changes from choco1/CI_workflow into choco2/main.
