name: Tag Workflow

on:
  push:
    branches:
      - main  # Activa el workflow en push a la rama principal

  workflow_dispatch:  # Trigger manual para seleccionar tipo de versión
    inputs:
      version_type:
        description: "Type of version to bump (major, minor, patch)"
        required: true
        default: "patch"

jobs:
  tag:
    if: ${{ github.repository == 'ch0cohub/choco-hub-1' }}
    name: Create Tag
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config user.name "FrancoDellAguila"
          git config user.email "francodellaguila@hotmail.com"

      - name: Determine Version Type from Commit Message
        id: version_type
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            # Trigger manual: Use the provided input
            echo "version_type=${{ github.event.inputs.version_type }}" >> $GITHUB_ENV
          else
            # Extract the last commit message
            last_commit=$(git log -1 --pretty=%B)
            echo "Last commit message: $last_commit"

            # Check for version keywords in the commit message
            if [[ "$last_commit" =~ "#major" ]]; then
              echo "version_type=major" >> $GITHUB_ENV
            elif [[ "$last_commit" =~ "#minor" ]]; then
              echo "version_type=minor" >> $GITHUB_ENV
            else
              echo "version_type=patch" >> $GITHUB_ENV
            fi
          fi

      - name: Generate Tag Version
        id: tag
        run: |
          # Extract the latest tag
          latest_tag=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
          echo "Latest tag: $latest_tag"

          # Parse the latest tag into components
          version_parts=(${latest_tag//v/})
          major=${version_parts[0]}
          minor=${version_parts[1]:-0}
          patch=${version_parts[2]:-0}

          # Determine the new version based on the version_type
          case "${{ env.version_type }}" in
            major) major=$((major + 1)); minor=0; patch=0 ;;
            minor) minor=$((minor + 1)); patch=0 ;;
            patch) patch=$((patch + 1)) ;;
            *) echo "Invalid version type"; exit 1 ;;
          esac

          new_tag="v${major}.${minor}.${patch}"
          echo "New tag: $new_tag"

          # Output the new tag
          echo "tag=$new_tag" >> $GITHUB_ENV

      - name: Create Tag
        run: |
          git tag -a ${{ env.tag }} -m "Release ${{ env.tag }}"
          git push origin ${{ env.tag }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Usar el token de GitHub para autenticación

#Funcionamiento:
#Automaticamente agrega 1 a patch en cada PR a main
#Si se agrega #major o #minor al commit cambia a la version correspondiente
#Tambien se puede hacer manualmente en la pagina de github actions
