name: Deploy Render

on:
    push:
      branches:
        - main
      tags:
        - 'v*' 

jobs:

  testing:
    if: ${{ github.repository == 'ch0cohub/choco-hub-2' }}
    name: Run Tests
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: uvlhub_root_password
          MYSQL_DATABASE: uvlhubdb_test
          MYSQL_USER: uvlhub_user
          MYSQL_PASSWORD: uvlhub_password
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:

    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Tests
      env:
        FLASK_ENV: testing
        MARIADB_HOSTNAME: 127.0.0.1
        MARIADB_PORT: 3306
        MARIADB_TEST_DATABASE: uvlhubdb_test
        MARIADB_USER: uvlhub_user
        MARIADB_PASSWORD: uvlhub_password
      run: |
        pytest app/modules/ --ignore-glob='*selenium*'

cleanup_connections:
    name: Cleanup Filess.io Database Connections
    runs-on: ubuntu-latest

    steps:
      # Instalar el cliente MySQL
      - name: Install MySQL client
        run: sudo apt-get update && sudo apt-get install -y mysql-client

      # Limpiar conexiones inactivas
      - name: Cleanup database connections
        env:
          DB_HOST: ${{ secrets.FILESS_DB_HOST }}
          DB_USER: ${{ secrets.FILESS_DB_USER }}
          DB_PASSWORD: ${{ secrets.FILESS_DB_PASSWORD }}
        run: |
          echo "Cleaning up orphaned connections on Filess.io..."
          mysql -h"$DB_HOST" -u"$DB_USER" -p"$DB_PASSWORD" -e "
          SELECT CONCAT('KILL ', id, ';')
          FROM information_schema.processlist
          WHERE user='$DB_USER' AND command='Sleep';" | mysql -h"$DB_HOST" -u"$DB_USER" -p"$DB_PASSWORD"

  deploy:
    if: ${{ github.repository == 'ch0cohub/choco-hub-2' }}
    name: Deploy to Render
    needs: testing
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Deploy to Render
        env:
          deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        run: |
          curl "$deploy_url"
